<a href="https://colab.research.google.com/github/CLiNTPELiX/brief18-py4/blob/main/brief18_Adrien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#import pandas as pd

class Pyfour:
  """
  DOCSTRING: Connect 4 game in Python using human vs human & human vs AI
  """
  pyfour_board_counter = 0
  numberOfPlayer = 0
  
  def __init__(self):
    """
    DOCSTRING: Increment a counter each init and sets default grid values
    """
    Pyfour.pyfour_board_counter += 1
    self.board_nb = Pyfour.pyfour_board_counter
    self.default_nboflines = 6
    self.default_nbofcolumns = 7
    self.board = np.zeros((self.default_nboflines, self.default_nbofcolumns), dtype=int)
    # self.board = [[0,0,0,0,0,0,0]
    #               [0,0,0,0,0,0,0]
    #               [0,0,0,0,0,0,0]
    #               [0,0,0,0,0,0,0]
    #               [0,0,0,0,0,0,0]
    #               [0,0,0,0,0,0,0]]

  def nbPlayer(self):
    """
    DOCSTRING: number of player(s)
    """
    while self.numberOfPlayer <= 0 or self.numberOfPlayer > 2:
          self.numberOfPlayer = int(input("Select number of player(s) 1 or 2 :"))
    return print("\n", f"The game will begin with {self.numberOfPlayer} player(s)", "\n")

  def displayBoard(self):
    """
    DOCSTRING: Display the board
    """
    board = self.board
    return print(board, "\n")

  def displayBoardNumber(self):
    """
    DOCSTRING: Display the board number
    """
    print(f"Board #{self.board_nb}", "\n")

  # def isAvailable(self, line, column):
  #   if line[column] == 0:
  #     return True
  #   return False

  def isColFull(self, column:int):
    if 0 not in self.board[:,column]:
      return True
    else:
      return False

  def colChoice(self, player:int, choice:int):
    """
    DOCSTRING: Inserting a coin into a col
    """
    
    if self.isBoardFull():
      return -2
    elif self.isColFull(choice):
      print(f'Column {choice} full')
      return -1
    else:
      column = self.board[:,choice]
      for i in range(0, self.default_nboflines)[::-1]:
        if column[i] == 0:
          column[i] = player
          break
      return i


  def isBoardFull(self):
    """
    DOCSTRING: 
    """
    return 0 not in self.board[0]

  def player_input(self, player, choice): #player = coin value (-1, 1) 
    """ 
    DOCSTRING: 
    """
    
    line = self.colChoice(player, choice) # Shall we play ?
    if line < 0:
      return line
    
    # Connect4 test on col
    column = self.board[:,choice]
    if np.all(column[line:line+4] == player) and len(column[line:line+4]) == 4:
      return self.board, 1, True

    # Connect4 test on line
    window = [player] * 4
    test = np.convolve(self.board[line, max(0, choice-3):choice+4], window)
    if player*4 in test:
      return self.board, 1, True #2
    
    # Connect4 test on diag
    board_padded = np.pad(self.board, (3, 3))
    #m8 = self.board[max(0, line-4):line+4, max(0, choice-4):choice+4]
    m8 = board_padded[line-3+3:line+4+3, choice-3+3:choice+4+3]

    d1 = np.diag(m8)
    d2 = np.diag(m8[::-1])
    
    #
    test = np.convolve(d1, window)
    if player*4 in test:
      return self.board, 1, True #3
    
    #
    test = np.convolve(d2, window)
    if player*4 in test:
      return self.board, 1, True

    # Random move for player2
    choice2 = np.random.randint(0, 7) # random player choice

    player2 = -player

    line = self.colChoice(player2, choice2)
    while line == -1: # if the line is full....
      line = self.colChoice(player2, choice2)
    if line == -2:
      return self.board, 0, True # Draw
    
    # Connect4 test on col
    column = self.board[:,choice2]
    if np.all(column[line:line+4] == player2) and len(column[line:line+4]) == 4:
      return self.board, -1, True
    # Connect4 test on line
    window = [player2] * 4
    test = np.convolve(self.board[line, max(0, choice2-3):choice2+4], window)
    if player2*4 in test:
      return self.board, -1, True
    
    # Connect4 test on diag
    board_padded = np.pad(self.board, (3, 3))
    m8 = board_padded[line-3+3:line+4+3, choice2-3+3:choice2+4+3]
    d1 = np.diag(m8)
    d2 = np.diag(m8[::-1])
    #
    test = np.convolve(d1, window)
    if player2*4 in test:
      return self.board, -1, True
    #
    test = np.convolve(d2, window)
    if player2*4 in test:
      return self.board, -1, True

    return self.board, 0, self.isBoardFull()

    # while (p1 <= 1) or (p1 > 7):
    #   p1 = int(input("Player 1 : Choose an empty column between (1 to 7) "))
    # return print(f"Player 1 chose {p1}")

In [ ]:
g = Pyfour()

#g.nbPlayer()
g.displayBoardNumber()
g.displayBoard()
#for i in range(0, 6): print(g.board[[i]])
#g.colChoice()


Board #1 

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] 



In [ ]:
g.colChoice()

Insert a coin into a column between 0 and 6 : 0


0

In [ ]:
g.displayBoard
#g.createBoard()
#g.displayBoard()

<bound method Pyfour.displayBoard of <__main__.Pyfour object at 0x7fb05a923110>>

In [ ]:
g = Pyfour()

print(g.player_input(player= 1, choice=3))

(array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0]]), 0, False)


In [ ]:
g.player_input(player= 1, choice=5)

(array([[ 0,  0,  0,  0,  0,  0, -1],
        [ 0,  0,  0,  0,  0,  0,  1],
        [ 0,  0,  0,  0,  0,  1, -1],
        [ 0,  0,  0,  0,  0,  1,  1],
        [-1,  0,  0, -1,  0,  1, -1],
        [-1,  0,  0,  1, -1,  1,  1]]), 1, True)

In [ ]:
g.displayBoard

<bound method Pyfour.displayBoard of <__main__.Pyfour object at 0x7f073e829bd0>>